### ISSUE TITLE
remove space in extension package file name

### ISSUE THREAD

**Issue by gferreira** [frankrolf/PangrammerHelper#1]
*continued from [this issue](http://github.com/robofont-mechanic/mechanic-2/issues/27)…*

there is currently a mismatch between the extension package file name in the [mechanic file]:

    PangrammerHelper.roboFontExt

and the actual file name in this repository:

    Pangrammer Helper.roboFontExt

I think removing the space here is better than adding a space there?

[mechanic file]: https://github.com/robofont-mechanic/mechanic-2-server/blob/master/_data/pangrammerHelper.yml

**Comment by ori-bendor** [comment]
Thanks @gferreira for opening this issue.
